// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAnimeInformation: (anime: string) => typedError<AnimeInformation, string>(__TAURI_INVOKE("get_anime_information", { anime })),
	saveAnimeInformation: (animeFolder: string, animeInformation: AnimeInformation) => typedError<number, string>(__TAURI_INVOKE("save_anime_information", { animeFolder, animeInformation })),
	searchAnime: (searchQuery: string) => typedError<SearchAnime[], string>(__TAURI_INVOKE("search_anime", { searchQuery })),
	getGenreList: () => __TAURI_INVOKE<GenreInformation[]>("get_genre_list"),
	getGenreListLibrary: () => typedError<Genre[], string>(__TAURI_INVOKE("get_genre_list_library")),
	getAnimesByGenre: (genre: string, page: number) => typedError<AnimeListPage, string>(__TAURI_INVOKE("get_animes_by_genre", { genre, page })),
	getAnimesByGenreLibrary: (page: number, perPage: number, sort: SortingMethod, genres: number[]) => typedError<AnimePaginate, string>(__TAURI_INVOKE("get_animes_by_genre_library", { page, perPage, sort, genres })),
	getLibraryAnimeInformation: (folderName: string) => typedError<LibraryAnimeInformation, string>(__TAURI_INVOKE("get_library_anime_information", { folderName })),
	libraryRemoveAnime: (folderName: string) => typedError<null, string>(__TAURI_INVOKE("library_remove_anime", { folderName })),
	libraryRemoveEpisode: (folderName: string, episodeName: string, resolution: Resolution) => typedError<null, string>(__TAURI_INVOKE("library_remove_episode", { folderName, episodeName, resolution })),
	getPaginateAnimesLibrary: (page: number, perPage: number, sort: SortingMethod) => typedError<AnimePaginate, string>(__TAURI_INVOKE("get_paginate_animes_library", { page, perPage, sort })),
	addSeasonalAnimeByDay: (day: Weekday, anime: string) => typedError<null, string>(__TAURI_INVOKE("add_seasonal_anime_by_day", { day, anime })),
	clearSeasonalAnime: () => typedError<null, string>(__TAURI_INVOKE("clear_seasonal_anime")),
	removeSeasonalAnimeByDay: (day: Weekday, anime: string) => typedError<null, string>(__TAURI_INVOKE("remove_seasonal_anime_by_day", { day, anime })),
	getSeasonalAnime: () => typedError<SeasonalAnime, string>(__TAURI_INVOKE("get_seasonal_anime")),
	getSeasonAnimes: (season: Season, year: number, page: number) => typedError<AnimeListPage, string>(__TAURI_INVOKE("get_season_animes", { season, year, page })),
	getOngoingAnime: (page: number) => typedError<AnimeOngoingPage, string>(__TAURI_INVOKE("get_ongoing_anime", { page })),
	downloadEpisode: (animeFolder: string, episode: EpisodeInformation, resolution: Resolution, platform: Platform) => typedError<string, string>(__TAURI_INVOKE("download_episode", { animeFolder, episode, resolution, platform })),
	downloadEpisodes: (animeFolder: string, episodes: EpisodeInformation[], resolution: Resolution, platform: Platform) => typedError<null, string>(__TAURI_INVOKE("download_episodes", { animeFolder, episodes, resolution, platform })),
	downloadLatestEpisode: (anime: string, resolution: Resolution, platform: Platform) => typedError<string, string>(__TAURI_INVOKE("download_latest_episode", { anime, resolution, platform })),
	downloadLatestEpisodes: (animes: string[], resolution: Resolution, platform: Platform) => typedError<null, string>(__TAURI_INVOKE("download_latest_episodes", { animes, resolution, platform })),
	checkInitStatus: () => typedError<InitStatus, string>(__TAURI_INVOKE("check_init_status")),
	cancelDownload: (id: string, resolution: Resolution) => typedError<null, string>(__TAURI_INVOKE("cancel_download", { id, resolution })),
	getVideosInArchive: () => typedError<ArchiveEntry[], string>(__TAURI_INVOKE("get_videos_in_archive")),
	extractVideosFromArchive: (outputDirectory: string, mappings: RenameMapping[]) => typedError<string[], string>(__TAURI_INVOKE("extract_videos_from_archive", { outputDirectory, mappings })),
	getEpisodeStreaming: (episodeUrl: string) => typedError<EpisodeStreamingInformation, string>(__TAURI_INVOKE("get_episode_streaming", { episodeUrl })),
	getMirrorLink: (mirrorInfo: MirrorData, nonce: string | null) => typedError<MirrorLink, string>(__TAURI_INVOKE("get_mirror_link", { mirrorInfo, nonce })),
	getVideoPath: (animeFolderName: string, episodeName: string, resolution: Resolution) => typedError<string, string>(__TAURI_INVOKE("get_video_path", { animeFolderName, episodeName, resolution })),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: UpdateSettingsPayload) => typedError<null, string>(__TAURI_INVOKE("save_settings", { settings })),
	pickFolder: () => typedError<string | null, string>(__TAURI_INVOKE("pick_folder")),
	setAnimeDownloadDirectory: () => typedError<boolean, string>(__TAURI_INVOKE("set_anime_download_directory")),
	setYoutubeDownloadDirectory: () => typedError<boolean, string>(__TAURI_INVOKE("set_youtube_download_directory")),
	getDashboardData: () => typedError<DashboardData, string>(__TAURI_INVOKE("get_dashboard_data")),
	getSeasons: () => __TAURI_INVOKE<Season[]>("get_seasons"),
	getSortingMethods: () => __TAURI_INVOKE<SortingMethod[]>("get_sorting_methods"),
	getPlatforms: () => __TAURI_INVOKE<Platform[]>("get_platforms"),
};

/** Events */
export const events = {
	downloadAnimeError: makeEvent<DownloadAnimeError>("download-anime-error"),
	downloadAnimeInfo: makeEvent<DownloadAnimeInfo>("download-anime-info"),
	downloadCancelled: makeEvent<DownloadCancelled>("download-cancelled"),
	downloadDone: makeEvent<DownloadDone>("download-done"),
	downloadError: makeEvent<DownloadError>("download-error"),
	downloadInfo: makeEvent<DownloadInfo>("download-info"),
	downloadProgress: makeEvent<DownloadProgress>("download-progress"),
};

/* Types */
export type Anime = {
	id: number,
	judul: string,
	japanese: string | null,
	produser: string | null,
	tanggal_rilis: string | null,
	studio: string | null,
	image_file: string,
	folder_name: string | null,
	genres: Genre[],
};

export type AnimeInformation = {
	image_url: string,
	judul: string,
	japanese: string,
	score: string,
	produser: string,
	tipe: string,
	status: string,
	tanggal_rilis: string,
	studio: string,
	genres: GenreInformation[],
	sinopsis: string[],
	episodes: EpisodeWithStatus[],
};

export type AnimeListInfo = {
	image_url: string,
	judul: string,
	anime_name: string,
	studio: string,
	score: string,
	musim_rilis: string,
	genres: GenreInformation[],
	sinopsis: string[],
};

export type AnimeListPage = {
	animes: AnimeListInfo[],
	current_page: number,
	max_page: number,
};

export type AnimeOngoingInfo = {
	image_url: string,
	judul: string,
	anime_name: string,
	day: string,
	date: string,
	latest_episode: string,
};

export type AnimeOngoingPage = {
	animes: AnimeOngoingInfo[],
	current_page: number,
	max_page: number,
};

export type AnimePaginate = {
	animes: Anime[],
	current_page: number,
	last_page: number,
	total: number,
};

export type AppSettings = {
	otakudesu_url?: string,
	anime_directory?: string,
	youtube_download_directory?: string,
	seasonal_anime?: SeasonalAnime,
};

export type ArchiveEntry = {
	original_path: string,
	size: number,
};

export type DashboardData = {
	dashboard_stats: DashboardStats,
	recently_change: Anime[],
	random_pick: Anime[],
	genre_distribution: GenreCount[],
};

export type DashboardStats = {
	total_anime: number,
	total_genre: number,
};

export type DownloadAnimeError = {
	anime_id: string,
	episode: EpisodeInformation,
	resolution: Resolution,
	message: string,
};

export type DownloadAnimeInfo = {
	anime_id: string,
	episode: EpisodeInformation,
	completed: boolean,
	resolution: Resolution,
};

export type DownloadCancelled = {
	id: string,
	resolution: Resolution,
};

export type DownloadDone = {
	id: string,
	resolution: Resolution,
	path: string,
};

export type DownloadError = {
	id: string,
	resolution: Resolution,
	message: string,
};

export type DownloadInfo = {
	id: string,
	resolution: Resolution,
	total_size: number | null,
};

export type DownloadProgress = {
	id: string,
	resolution: Resolution,
	downloaded: number | null,
	total: number | null,
};

export type EpisodeInformation = {
	name: string,
	date: string,
	url: string,
};

export type EpisodeStreamingInformation = {
	episode_information: EpisodeInformation,
	anime_name: string,
	anime_folder: string,
	episodes: EpisodeInformation[],
	default_mirror: string,
	mirrors: ResolutionMirror[],
};

export type EpisodeWithStatus = {
	info: EpisodeInformation,
	downloaded_resolutions: Resolution[],
};

export type Genre = {
	id: number,
	name: string,
};

export type GenreCount = {
	name: string,
	total: number,
};

export type GenreInformation = {
	name: string,
	display: string,
};

export type InitStatus = {
	is_initialized: boolean,
	has_store_anime_directory: boolean,
	has_youtube_download_directory: boolean,
};

export type LibraryAnimeInformation = {
	anime: Anime,
	episodes: LibraryEpisodeInformation[],
};

export type LibraryEpisodeInformation = {
	name: string,
	resolutions: Resolution[],
};

export type Mirror = {
	name: string,
	data: MirrorData,
};

export type MirrorData = {
	id: number,
	i: number,
	q: string,
};

export type MirrorLink = {
	url: string,
	nonce: string,
};

export type Platform = "Pdrain" | "Mega" | "DesuDrive";

export type RenameMapping = {
	original_path: string,
	new_name: string,
};

export type Resolution = "P360" | "P480" | "P720";

export type ResolutionMirror = {
	resolution: string,
	mirrors: Mirror[],
};

export type SearchAnime = {
	judul: string,
	anime_name: string,
	image_url: string,
	genre: GenreInformation[],
	status: string,
};

export type Season = "Winter" | "Summer" | "Fall" | "Spring";

export type SeasonalAnime = {
	monday?: string[],
	tuesday?: string[],
	wednesday?: string[],
	thursday?: string[],
	friday?: string[],
	saturday?: string[],
	sunday?: string[],
};

export type SortingMethod = "release_date_desc" | "release_date_asc" | "title_asc" | "title_desc" | "recently_added" | "oldest_added" | "recently_modified" | "oldest_modified";

export type UpdateSettingsPayload = {
	otakudesu_url: string | null,
	anime_directory: string | null,
	youtube_download_directory: string | null,
	seasonal_anime: SeasonalAnime | null,
};

export type Weekday = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

